name: date_util
description: A simple API with a complete set of date helper methods  
             not available in the DateTime API hence,production is
             made easier when working with dates.
version: 0.1.0
homepage: https://github.com/corpsgeek/Date-Utility
author: Adetu Ridwan, Egbesola Anthony <bethetechnology@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
